version: '3'

services:
  db:
    image: postgres:latest
    container_name: apollo_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apollo
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: apollo_web
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
